openapi: 3.0.1
info:
  title: My API
  version: v1
paths:
  /api/Login:
    get:
      tags:
        - Login
      parameters:
        - name: Username
          in: query
          schema:
            type: string
        - name: Password
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
components: {}
